[[headers]]
for = "/*"
  [headers.values]
  X-Frame-Options = "SAMEORIGIN"
  Content-Security-Policy = "frame-ancestors 'self'"

[[headers]]
for = "/admin/*"
  [headers.values]
  Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; frame-ancestors 'self';"

